// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: product/productservice.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_product_productservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{0}
}

func (x *Audit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Audit) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Audit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Audit) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Badge         string                 `protobuf:"bytes,4,opt,name=badge,proto3" json:"badge,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice *float64               `protobuf:"fixed64,6,opt,name=original_price,json=originalPrice,proto3,oneof" json:"original_price,omitempty"`
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,8,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Features      []string               `protobuf:"bytes,11,rep,name=features,proto3" json:"features,omitempty"`
	// Dynamic attributes for anything not strictly captured in the UI yet
	Attributes    map[string]string `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Audit         *Audit            `protobuf:"bytes,13,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_productservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetOriginalPrice() float64 {
	if x != nil && x.OriginalPrice != nil {
		return *x.OriginalPrice
	}
	return 0
}

func (x *Product) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Product) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Product) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetAudit() *Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"` // Assuming SKU is generated by the client or backend
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Badge         string                 `protobuf:"bytes,4,opt,name=badge,proto3" json:"badge,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice *float64               `protobuf:"fixed64,6,opt,name=original_price,json=originalPrice,proto3,oneof" json:"original_price,omitempty"`
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,8,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Features      []string               `protobuf:"bytes,11,rep,name=features,proto3" json:"features,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_productservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetOriginalPrice() float64 {
	if x != nil && x.OriginalPrice != nil {
		return *x.OriginalPrice
	}
	return 0
}

func (x *CreateProductRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateProductRequest) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *CreateProductRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *CreateProductRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"` // Required to identify which product to update
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Category      *string                `protobuf:"bytes,3,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Badge         *string                `protobuf:"bytes,4,opt,name=badge,proto3,oneof" json:"badge,omitempty"`
	Price         *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	OriginalPrice *float64               `protobuf:"fixed64,6,opt,name=original_price,json=originalPrice,proto3,oneof" json:"original_price,omitempty"`
	Rating        *float64               `protobuf:"fixed64,7,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	ReviewCount   *int32                 `protobuf:"varint,8,opt,name=review_count,json=reviewCount,proto3,oneof" json:"review_count,omitempty"`
	Image         *string                `protobuf:"bytes,9,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Description   *string                `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Features      []string               `protobuf:"bytes,11,rep,name=features,proto3" json:"features,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_productservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateProductRequest) GetBadge() string {
	if x != nil && x.Badge != nil {
		return *x.Badge
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetOriginalPrice() float64 {
	if x != nil && x.OriginalPrice != nil {
		return *x.OriginalPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *UpdateProductRequest) GetReviewCount() int32 {
	if x != nil && x.ReviewCount != nil {
		return *x.ReviewCount
	}
	return 0
}

func (x *UpdateProductRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *UpdateProductRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_productservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type SearchProductsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Query     string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageSize  int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Allows searching by specific facets (e.g. {"category": "Electronics"})
	AttributeFilters map[string]string `protobuf:"bytes,4,rep,name=attribute_filters,json=attributeFilters,proto3" json:"attribute_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_product_productservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{5}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchProductsRequest) GetAttributeFilters() map[string]string {
	if x != nil {
		return x.AttributeFilters
	}
	return nil
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_productservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{6}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_product_productservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_productservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_productservice_proto_rawDescGZIP(), []int{7}
}

func (x *SearchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SearchProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_product_productservice_proto protoreflect.FileDescriptor

const file_product_productservice_proto_rawDesc = "" +
	"\n" +
	"\x1cproduct/productservice.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x05Audit\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\"\xdc\x03\n" +
	"\aProduct\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05badge\x18\x04 \x01(\tR\x05badge\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12*\n" +
	"\x0eoriginal_price\x18\x06 \x01(\x01H\x00R\roriginalPrice\x88\x01\x01\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12!\n" +
	"\freview_count\x18\b \x01(\x05R\vreviewCount\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1a\n" +
	"\bfeatures\x18\v \x03(\tR\bfeatures\x128\n" +
	"\n" +
	"attributes\x18\f \x03(\v2\x18.Product.AttributesEntryR\n" +
	"attributes\x12\x1c\n" +
	"\x05audit\x18\r \x01(\v2\x06.AuditR\x05audit\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_original_price\"\xd8\x03\n" +
	"\x14CreateProductRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05badge\x18\x04 \x01(\tR\x05badge\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12*\n" +
	"\x0eoriginal_price\x18\x06 \x01(\x01H\x00R\roriginalPrice\x88\x01\x01\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12!\n" +
	"\freview_count\x18\b \x01(\x05R\vreviewCount\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1a\n" +
	"\bfeatures\x18\v \x03(\tR\bfeatures\x12E\n" +
	"\n" +
	"attributes\x18\f \x03(\v2%.CreateProductRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_original_price\"\xe0\x04\n" +
	"\x14UpdateProductRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x03 \x01(\tH\x01R\bcategory\x88\x01\x01\x12\x19\n" +
	"\x05badge\x18\x04 \x01(\tH\x02R\x05badge\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x03R\x05price\x88\x01\x01\x12*\n" +
	"\x0eoriginal_price\x18\x06 \x01(\x01H\x04R\roriginalPrice\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\a \x01(\x01H\x05R\x06rating\x88\x01\x01\x12&\n" +
	"\freview_count\x18\b \x01(\x05H\x06R\vreviewCount\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\t \x01(\tH\aR\x05image\x88\x01\x01\x12%\n" +
	"\vdescription\x18\n" +
	" \x01(\tH\bR\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bfeatures\x18\v \x03(\tR\bfeatures\x12E\n" +
	"\n" +
	"attributes\x18\f \x03(\v2%.UpdateProductRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_categoryB\b\n" +
	"\x06_badgeB\b\n" +
	"\x06_priceB\x11\n" +
	"\x0f_original_priceB\t\n" +
	"\a_ratingB\x0f\n" +
	"\r_review_countB\b\n" +
	"\x06_imageB\x0e\n" +
	"\f_description\"(\n" +
	"\x14DeleteProductRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\"\x89\x02\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12Y\n" +
	"\x11attribute_filters\x18\x04 \x03(\v2,.SearchProductsRequest.AttributeFiltersEntryR\x10attributeFilters\x1aC\n" +
	"\x15AttributeFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x0fProductResponse\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\"f\n" +
	"\x16SearchProductsResponse\x12$\n" +
	"\bproducts\x18\x02 \x03(\v2\b.ProductR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken2\x8f\x02\n" +
	"\x0eProductService\x12:\n" +
	"\rCreateProduct\x12\x15.CreateProductRequest\x1a\x10.ProductResponse\"\x00\x12:\n" +
	"\rUpdateProduct\x12\x15.UpdateProductRequest\x1a\x10.ProductResponse\"\x00\x12@\n" +
	"\rDeleteProduct\x12\x15.DeleteProductRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\x0eSearchProducts\x12\x16.SearchProductsRequest\x1a\x17.SearchProductsResponse\"\x00BAZ?github.com/phuthien0308/ordering-base/contracts/product;productb\x06proto3"

var (
	file_product_productservice_proto_rawDescOnce sync.Once
	file_product_productservice_proto_rawDescData []byte
)

func file_product_productservice_proto_rawDescGZIP() []byte {
	file_product_productservice_proto_rawDescOnce.Do(func() {
		file_product_productservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_productservice_proto_rawDesc), len(file_product_productservice_proto_rawDesc)))
	})
	return file_product_productservice_proto_rawDescData
}

var file_product_productservice_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_product_productservice_proto_goTypes = []any{
	(*Audit)(nil),                  // 0: Audit
	(*Product)(nil),                // 1: Product
	(*CreateProductRequest)(nil),   // 2: CreateProductRequest
	(*UpdateProductRequest)(nil),   // 3: UpdateProductRequest
	(*DeleteProductRequest)(nil),   // 4: DeleteProductRequest
	(*SearchProductsRequest)(nil),  // 5: SearchProductsRequest
	(*ProductResponse)(nil),        // 6: ProductResponse
	(*SearchProductsResponse)(nil), // 7: SearchProductsResponse
	nil,                            // 8: Product.AttributesEntry
	nil,                            // 9: CreateProductRequest.AttributesEntry
	nil,                            // 10: UpdateProductRequest.AttributesEntry
	nil,                            // 11: SearchProductsRequest.AttributeFiltersEntry
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
}
var file_product_productservice_proto_depIdxs = []int32{
	12, // 0: Audit.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: Audit.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: Product.attributes:type_name -> Product.AttributesEntry
	0,  // 3: Product.audit:type_name -> Audit
	9,  // 4: CreateProductRequest.attributes:type_name -> CreateProductRequest.AttributesEntry
	10, // 5: UpdateProductRequest.attributes:type_name -> UpdateProductRequest.AttributesEntry
	11, // 6: SearchProductsRequest.attribute_filters:type_name -> SearchProductsRequest.AttributeFiltersEntry
	1,  // 7: ProductResponse.product:type_name -> Product
	1,  // 8: SearchProductsResponse.products:type_name -> Product
	2,  // 9: ProductService.CreateProduct:input_type -> CreateProductRequest
	3,  // 10: ProductService.UpdateProduct:input_type -> UpdateProductRequest
	4,  // 11: ProductService.DeleteProduct:input_type -> DeleteProductRequest
	5,  // 12: ProductService.SearchProducts:input_type -> SearchProductsRequest
	6,  // 13: ProductService.CreateProduct:output_type -> ProductResponse
	6,  // 14: ProductService.UpdateProduct:output_type -> ProductResponse
	13, // 15: ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	7,  // 16: ProductService.SearchProducts:output_type -> SearchProductsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_product_productservice_proto_init() }
func file_product_productservice_proto_init() {
	if File_product_productservice_proto != nil {
		return
	}
	file_product_productservice_proto_msgTypes[1].OneofWrappers = []any{}
	file_product_productservice_proto_msgTypes[2].OneofWrappers = []any{}
	file_product_productservice_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_productservice_proto_rawDesc), len(file_product_productservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_productservice_proto_goTypes,
		DependencyIndexes: file_product_productservice_proto_depIdxs,
		MessageInfos:      file_product_productservice_proto_msgTypes,
	}.Build()
	File_product_productservice_proto = out.File
	file_product_productservice_proto_goTypes = nil
	file_product_productservice_proto_depIdxs = nil
}
